spring:
  datasource:
    url: jdbc:postgresql://caboose.proxy.rlwy.net:17753/railway
    username: postgres
    password: jyVemwwBSpQEoLxdyLKIzCtPKMyIenbm
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  web:
    cors:
      allowed-origins: "https://web-production-4deb.up.railway.app"  # URL do seu Swagger UI
      allowed-methods: "*"
      allowed-headers: "*"