spring:
  datasource:
    url: jdbc:postgresql://caboose.proxy.rlwy.net:17753/railway
    username: postgres
    password: jyVemwwBSpQEoLxdyLKIzCtPKMyIenbm
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect